In [1]:
import logging
import os
import sys
import traceback

from hydra import initialize, compose
import numpy as np
from omegaconf import DictConfig
import scanpy as sc
import torch

import sys 
sys.path.insert(0, "../../../../../shared_utils")
from experiment_utils import get_forward_model

In [2]:
with initialize(config_path="../../../../../inverse/loss_guidance/config", version_base=None):
    config = compose(config_name="run_inverse",
                    overrides=[
                        "paths=bloodplus"
                    ])s

In [9]:
logger = logging.getLogger(__name__)

forward_model, (
    flow_matching,
    target_prediction_model
) = get_forward_model(config, logger=logger)

In [10]:
# Classify both training and validation anndata

In [23]:
train_adata = flow_matching.train_data.adata

In [24]:
validation_adata = flow_matching.validation_data['random_state=42-split_to_retrieve=0-test_size=0.3-K=3'].adata

In [26]:
train_adata.obs.head()

,experiment_number,replicate,date,cytometer,cytometer_serial_no,well_id,count_beads,cell_counts,experiment_id,740-yp_[µm],...,FSC-H :: FSC - Height,FSC-W :: FSC - Width,SSC-A :: SSC - Area,SSC-H :: SSC - Height,SSC-W :: SSC - Width,TIME,NA,AF Index,batch,7-AAD
31662-433,1091,3,06-DEC-2024,LE-ID7000C,2803032,B10,1090,153983,LPHO03b,5,...,184460.0,245.903656,172552.937500,104153.5,213.451950,30.170439,10954.522461,28.0,433,184.928726
57003-499,130,1,12-MAR-2025,LE-ID7000C,2803032,D08,1386,56008,LPHO04,5,...,217542.5,253.773453,317352.281250,209650.0,194.071259,33.208538,12707.878906,29.0,499,-2333.371094
55389-567,141,4,12-MAR-2025,LE-ID7000C,2803032,E04,1216,147500,LPHO05,5,...,173268.5,243.260559,209203.656250,142000.0,188.884094,13.980380,8176.539062,10.0,567,1759.553467
60542-96,189,1,16-JAN-2025,LE-ID7000C,2803032,G02,833,184572,JAR02,5,...,142482.0,214.152802,150769.328125,96752.0,201.469299,14.705660,3905.304688,9.0,96,130.074158
48555-519,133,4,12-MAR-2025,LE-ID7000C,2803032,F08,1413,95984,LPHO04,5,...,153636.0,260.656555,163692.484375,102144.0,205.461472,20.966240,18669.751953,15.0,519,-511.184723

In [28]:
validation_adata.obs.head()

,experiment_number,replicate,date,cytometer,cytometer_serial_no,well_id,count_beads,cell_counts,experiment_id,740-yp_[µm],...,FSC-H :: FSC - Height,FSC-W :: FSC - Width,SSC-A :: SSC - Area,SSC-H :: SSC - Height,SSC-W :: SSC - Width,TIME,NA,AF Index,batch,7-AAD
170602-675,2138,5,26-MAR-2025,LE-ID7000C,2803032,B05,1153,169282,LPHO05,5,...,188186.0,233.420578,245354.437500,154060.0,203.569824,40.722401,13281.574219,50.0,675,-67.835953
244076-412,1178,3,06-DEC-2024,LE-ID7000C,2803032,E10,1061,182904,LPHO03b,5,...,251093.5,251.870560,249165.906250,130428.5,246.131821,26.048079,8620.533203,18.0,412,-408.586639
133834-555,139,3,12-MAR-2025,LE-ID7000C,2803032,D02,1197,160002,LPHO05,5,...,183112.0,242.798981,206392.171875,117369.5,225.451141,36.833920,3795.799805,6.0,555,-177.275436
32901-276,67,3,30-NOV-2024,LE-ID7000C,2803032,D04,995,33055,LPHO03a,5,...,186951.5,263.420288,243958.687500,140230.0,224.098083,38.157318,12697.850586,17.0,276,39.914955
22548-99,123,1,16-JAN-2025,LE-ID7000C,2803032,G05,898,44885,JAR02,5,...,240715.0,290.809723,359322.687500,184652.0,251.585983,12.341960,6920.663086,9.0,99,171.121292